### ISSUE TITLE
API limit number of items returned is 200

### ISSUE THREAD

**Issue by sajkec** [mediamosa/mediamosa#244]
We have found that using API, there is a limit to 200 items (assets) returned with the same query. Is it possible to change this limit to higher number? 
Our frontend does some queries which have more than 200 items in them, and we need to do offsetting right now, but this takes a lot of waiting for end users who wait for results.

**Comment by rblanker** [comment]
The 200 limit is by design, there is not a lot you can do about it unless you change one setting in mediamosa_settings::LIMIT_MAX in sites/all/modules/mediamosa/mediamosa.settings.class.inc.

Remember that this is by design because more than 1000 really slows down mediamosa and you will get issues with PHP memory.

**Comment by sajkec** [comment]
Thanks for the explanation.
